__default__:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 1
  partition: debug
  cpus_per_task: 1
estimate:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug
ancient_genomes:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug
ancient_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug
