# Basic config File
# Where is the workflow
wdir: "/vol/cloud/geogenetics/repos/metaDMG-simulations"
# Where is the data
sdir: "/vol/cloud/geogenetics/metaDMG-sims/synthetic-data/data"
# Where is the output
rdir: "/vol/cloud/geogenetics/metaDMG-sims/synthetic-data/results"

# A list of all the samples to be simulated
sample_file_read: "/vol/cloud/geogenetics/metaDMG-sims/synthetic-data/assets/metaDMGsamplelist-test.tsv"

###############################################################################
#
# Common config values
#
###############################################################################

# aMGSIM config files
fb_config_file: "/vol/cloud/geogenetics/metaDMG-sims/synthetic-data/assets/config/fb-config.yml"
ag_config_file: "/vol/cloud/geogenetics/metaDMG-sims/synthetic-data/assets/config/ag-config.yml"
ar_config_file: "/vol/cloud/geogenetics/metaDMG-sims/synthetic-data/assets/config/ar-config.yml"
cpus: 16
# aMGSIM config files
# fb_config
genome_paths: /vol/cloud/geogenetics/metaDMG-sims/synthetic-data/assets/genome-paths-list.tsv
names_dmp: /vol/cloud/geogenetics/DBs/gtdb/r202/data/vanilla-organelles-virus/pkg/taxonomy/names.dmp
nodes_dmp: /vol/cloud/geogenetics/DBs/gtdb/r202/data/vanilla-organelles-virus/pkg/taxonomy/nodes.dmp
acc2taxid: /vol/cloud/geogenetics/DBs/gtdb/r202/data/vanilla-organelles-virus/pkg/taxonomy/acc2taxid.map.gz
max_genomes_nondamaged: 10
max_genomes_damaged: 10

# ag_config
num_reads: [1e6, 5e6, 10e6]
seq_library: ["double"]
libprep: ["double", "single"]
